### ISSUE TITLE
a better way to show the invite

### ISSUE THREAD

**Issue by ghost** [Speyd3r/MeekPlush-Bot#2]
Try to modify how MeekPlush shows his invite!
a bit like this for example:
`"[This is my invite!](https://discordapp.com/oauth2/authorize?client_id=465675368775417856&scope=bot&permissions=67497025)!"`
and add an image or stuff like that!

**Comment by Sekoree** [comment]
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.............................

yes

**Comment by Chivi19** [comment]
sorry, forgot to say that it would be nice having the invite in an embed
